deploy/nacos/nacos-pvc-nfs.yaml
haha, I think the naming is that you unintended misspelled.
=> edited potential name question.

quick-startup.sh
=> redundant words

deploy/mysql/mysql-slave-local.yaml
change hostPath to "/var/lib/mysql-slave"
otherwise, "/var/lib/mysql" conflict with mysql-master-local.yaml
=> update mysql-slave-local.yaml, change hostPath to "/var/lib/mysql-slave"

deploy/mysql/mysql-master-ceph.yaml, deploy/mysql/mysql-slave-ceph.yaml
不太清楚这个你们那边保留这个 volumeMounts 的意图。是不是预留做一些其他用途？如果是，请 close 这个PR.
=> Why this volumeMounts

openshift/nacos-template.yaml, openshift/readme.md
add  install nacos  on openshift
=> add  install nacos  on openshift

deploy/nfs/deployment.yaml
- Change apiVersion apps/v1
- Add spec.selector
- Refine yaml format
- k8s 1.16.2 minikube environments
=> support k8s 1.16

helm/templates/NOTES.txt
Add missing parentheses in helm/templates/NOTES.txt
=> fix: Add missing parentheses

README-CN.md, README.md
README文件中有一处拼写错误。deploy写成了depoly。
=> modify README.md README-CN.md nacos-pvc-nfs.yaml path

README-CN.md, README.md
Prevent "sed: -i may not be used with stdin" when running on Macos.
=> Fix some minor issues in README*.md files

operator/pkg/service/operator/Kind.go, operator/pkg/service/operator/operaror.go
Signed-off-by: shenkonghui <shenkh1992@gmail.com>
=> fix: fix use ip failed when init database with mysql, fixes #272

README-CN.md, README.md
=> replace the service discovery api in the reademe

operator/chart/nacos/templates/nacos.yaml, operator/chart/nacos/values.yaml
* values.yaml文件中的一行注释似乎不太正确
* crd中并没有定义 imagePullPolicy 此字段，在使用chart安装时会报错。
=> fix<nacos chart>:fix nacos chart bugs

operator/pkg/service/operator/Kind.go
=> fix: operator env domain no effect

operator/Dockerfile, operator/controllers/nacos_controller.go, operator/controllers/suite_test.go, operator/go.mod, operator/pkg/service/nacos/cluster.go, operator/pkg/service/operator/Kind.go
解决 双栈 k8s环境下 nacos operator启动nacos不成功的问题。详见issue:https://github.com/nacos-group/nacos-k8s/issues/346
=> nacos operator support dual stack k8s environment

operator/controllers/nacos_controller.go
Signed-off-by: yanru.lv <yanru.lv@daocloud.io>
=> [fix]requeueafter time

helm/templates/statefulset.yaml, helm/values.yaml
这个 pr 仅给 nacos 的 Statefulset 设置了 podManagementPolicy 为 `Parallel`
用于解决这个 issues 的问题 https://github.com/nacos-group/nacos-k8s/issues/349
=> enhancement: Set Parallel to podManagementPolicy

.github/workflows/operator-build.yaml, operator/Dockerfile
Update the github action for release to let docker images support multi arch, both amd64 and arm64
=> Update release process to support multi arch docker images

operator/chart/nacos-operator/nacos-operator-all.yaml
还有一个地方的ClusterRole没有加
https://github.com/nacos-group/nacos-k8s/pull/371
=> add leases rules in nacos-operator-all.yaml

operator/api/v1alpha1/nacos_types.go, operator/config/crd/bases/nacos.io_nacos.yaml, operator/pkg/service/operator/Kind.go
=> add funtion mode

README-CN.md, README.md
README中数据库脚本链接失效 https://github.com/nacos-group/nacos-k8s/issues/394
=> 更新README中数据库初始化语句链接

operator/pkg/service/k8s/statefulset.go
=> 修复当修改nacos cr部分参数不会自动生效的问题
